from typing import Collection, Protocol

from src.domain.models import Chunk, CVInfo, ExtractedCV


class BlobStore(Protocol):
    def upload(self, filename: str, data: bytes) -> None: ...
    def download(self, filename: str) -> bytes: ...
    def delete(self, filename: str) -> None: ...


class PdfExtractor(Protocol):
    def extract(self, data: bytes, filename: str) -> ExtractedCV: ...


class Embedder(Protocol):
    def embed(self, texts: list[str]) -> list[list[float]]: ...


class VectorIndex(Protocol):
    def ensure(self) -> None: ...
    def get_hash(self, cv_id: str) -> str | None: ...
    def delete_cv(self, cv_id: str, keep_ids: Collection[str] = ()) -> None: ...
    def upload(self, chunks: list[Chunk]) -> None: ...
    def list_cvs(self) -> list[CVInfo]: ...
